specVersion: 0.2.0
name: acala-tokens
version: 1.0.0
description: 'statistics tokens data'
repository: 'https://github.com/AcalaNetwork/acala-tokens-subql'
schema: 
    file: ./schema.graphql
network:
  genesisHash: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  dictionary: https://api.subquery.network/sq/AcalaNetwork/karura-dictionary
  endpoint: wss://karura.api.onfinality.io/public-ws
  chaintypes:
    file: './src/chain-types.js'
dataSources:
    - kind: substrate/Runtime
      startBlock: 1
      mapping:
        file: './dist/index.js'
        handlers:
          - handler: handleBalancesTransfer
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Transfer
          - handler: handleBalancesDeposit
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Deposit
          - handler: handleBalancesWithdraw
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Withdraw
          - handler: handleBalancesDustLost
            kind: substrate/EventHandler
            filter:
              module: balances
              method: DustLost
          - handler: handleBalancesReserved
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Reserved
          - handler: handleBalancesUnreserved
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Unreserved
          - handler: handleBalancesReserveRepatriated
            kind: substrate/EventHandler
            filter:
              module: balances
              method: ReserveRepatriated
          - handler: handleCurrenciesTransfer
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: Transferred
          - handler: handleCurrenciesDeposite
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: Deposited
          - handler: handleCurrenciesWithdrawn
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: Withdrawn
          - handler: handleDustSwept
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: DustSwept
          - handler: handleBalanceUpdatedEvent
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: BalanceUpdated
